def shared_pods
    pod 'Moya', '~> 14.0.0'
    pod 'Kingfisher', '~> 5.14.0'
    pod 'SwiftLint', '~> 0.39.2'
end

target 'ExampleCrossAppleOS' do
    platform :osx, '10.12'
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for ExampleCrossAppleOS
    shared_pods

end

target 'ExampleCrossAppleOSTouch' do
    platform :ios, '10.0'
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for ExampleCrossAppleOSTouch
    shared_pods

end

target 'ExampleIOS' do
    platform :ios, '10.0'
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for ExampleIOS
    shared_pods

    target 'ExampleIOSTests' do
        inherit! :search_paths
        # Pods for testing
    end

    target 'ExampleIOSUITests' do
        inherit! :search_paths
        # Pods for testing
    end

end

target 'ExampleMacOS' do
    platform :osx, '10.12'
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for ExampleMacOS
    shared_pods

    target 'ExampleMacOSTests' do
        inherit! :search_paths
        # Pods for testing
    end

    target 'ExampleMacOSUITests' do
        inherit! :search_paths
        # Pods for testing
    end

end
